version: '3'

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate golang code from proto files"
    cmds:
      - protoc -I=protos protos/proto/bookcenter/*.proto --go_out=protos/gen/go/ --go_opt=paths=source_relative --go-grpc_out=protos/gen/go/ --go-grpc_opt=paths=source_relative